/* Populating table of seller */

INSERT INTO `seller` (`name`) VALUES ("Hammett Carroll"),("Nicholas Flores"),("Burton Munoz"),("Coby Marshall"),("Hu Wilkinson"),("Xenos Craig"),("Xavier Baldwin"),("Chancellor Douglas"),("Uriah Farmer"),("Melvin Aguirre");
INSERT INTO `seller` (`name`) VALUES ("Wayne Benson"),("Walter Perkins"),("Grady Wolf"),("Isaac Curtis"),("Perry Olsen"),("Macaulay Hunt"),("Silas Mckinney"),("Caesar Good"),("Zachery Lawrence"),("Malik Mccullough");
INSERT INTO `seller` (`name`) VALUES ("Abel Conner"),("Brenden Duke"),("Kasimir Frye"),("Abdul Mcpherson"),("Slade Suarez"),("Aidan Parrish"),("Steven Goodman"),("Jacob Powell"),("Kevin Nieves"),("Edward Wells");
INSERT INTO `seller` (`name`) VALUES ("Malik Kaufman"),("Blaze Norman"),("Arthur Paul"),("Beau Newman"),("Mark Chandler"),("Omar Snider"),("Tate Buckley"),("Xenos Daniels"),("Macaulay Mcclain"),("Christian Sharpe");
INSERT INTO `seller` (`name`) VALUES ("Cruz Webb"),("Phelan Stevenson"),("Jesse Bradshaw"),("Clarke Hogan"),("Lev Poole"),("Jerome Rasmussen"),("Logan Burgess"),("Zahir Taylor"),("Barry Young"),("Davis Dunlap");
INSERT INTO `seller` (`name`) VALUES ("Fitzgerald Moran"),("Levi Ellis"),("Baxter Willis"),("Henry Moore"),("Devin Rosario"),("Colby Underwood"),("Lane Little"),("Graham Morales"),("Brennan Marquez"),("Robert Church");
INSERT INTO `seller` (`name`) VALUES ("Luke Gray"),("Zeus Aguirre"),("Cole Gomez"),("Brennan Weaver"),("Matthew Myers"),("Thomas Fitzpatrick"),("Neil Blackburn"),("Merritt Rodriguez"),("Driscoll Ratliff"),("Stewart Sampson");
INSERT INTO `seller` (`name`) VALUES ("Nissim Cotton"),("Kato Gutierrez"),("Salvador Miller"),("Chancellor Saunders"),("Rogan Graves"),("Henry Riddle"),("Timothy Obrien"),("Christian Hurst"),("Merritt Brooks"),("Hall Harvey");
INSERT INTO `seller` (`name`) VALUES ("Timothy Curtis"),("Walker Bryan"),("Edward Herman"),("Brennan Reynolds"),("Odysseus Maddox"),("Orson Francis"),("William Roy"),("Tanner Gould"),("Dylan Lawson"),("Grant Morton");
INSERT INTO `seller` (`name`) VALUES ("Darius Fields"),("Ignatius Buckner"),("Philip Kidd"),("Kevin Jackson"),("Reed Goodwin"),("Thomas Greene"),("Timon Waller"),("Raphael Campbell"),("Tyler Stephens"),("Geoffrey Bass");